
### Peticion sensores de fuerza
POST http://localhost:3000/getSensorsServo
Content-Type: application/json

[
  {
    "NumServo": 1
  },
  {
    "NumServo": 2
  }
]


### Peticion sensores de fuerza
POST http://localhost:3000/setServosActuator
Content-Type: application/json

[
  {
    "NumServo": 1,
    "Actuator": 0
  },
  {
    "NumServo": 2,
    "Actuator": 0
  }
]

